import { expect, type Browser, type Page } from '@playwright/test'

export async function exerciseClassroom(page: Page, browser: Browser, slideName: string) {
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByRole('menuitem', { name: 'New folder', exact: true }).click()
  const folder = page.getByRole('dialog', { name: 'New folder', exact: true })
  await folder.getByLabel('Name', { exact: true }).fill('Synthetic teaching class')
  await folder.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(folder).not.toBeVisible()
  await page.getByRole('button', { name: `More actions for ${slideName}`, exact: true }).click()
  await page.getByRole('menuitem', { name: 'Move', exact: true }).click()
  const move = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Move slides', exact: true }) })
  await expect(move).toHaveAccessibleName('Move slides')
  await move.getByRole('combobox', { name: 'Destination', exact: true }).selectOption({ label: 'Synthetic teaching class' })
  await move.getByRole('button', { name: 'Move', exact: true }).click()
  await expect(move).not.toBeVisible()
  await page.getByRole('button', { name: 'Classroom', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search class folders' }).fill('Synthetic teaching')
  await page.getByRole('radio', { name: /Synthetic teaching class.*1 slide/ }).check()
  await page.getByRole('button', { name: 'Prepare classroom with 1 slide', exact: true }).click()
  const invitation = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Review slides and join class' }) })
  const inviteUrl = await invitation.getByRole('link').getAttribute('href')
  const accessCode = await invitation.locator('strong').innerText()
  if (!inviteUrl) throw new Error('Visible Classroom invitation link missing')
  await invitation.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Start live class', exact: true }).click()
  await invitation.getByRole('button', { name: 'Close', exact: true }).click()

  const studentContext = await browser.newContext({ baseURL: process.env.PATHLAB_E2E_BASE_URL })
  const recovered = await page.context().newPage()
  try {
    const student = await studentContext.newPage()
    await student.goto(inviteUrl)
    await student.getByLabel('Access code', { exact: true }).fill(accessCode)
    await student.getByRole('button', { name: 'Open slide review', exact: true }).click()
    await student.getByRole('button', { name: 'Join live class', exact: true }).click()
    await expect(student.locator('.openseadragon-canvas canvas').first()).toBeVisible()
    await expect(page.getByLabel('1 students', { exact: true })).toBeVisible()

    await recovered.goto('/admin')
    await recovered.getByRole('button', { name: 'Classroom', exact: true }).click()
    await recovered.getByRole('button', { name: `Resume classroom ${accessCode}`, exact: true }).click()
    await expect(recovered.getByLabel('1 students', { exact: true })).toBeVisible()
    await expect(recovered.locator('.openseadragon-canvas canvas').first()).toBeVisible()
    await student.reload()
    await expect(student.locator('.openseadragon-canvas canvas').first()).toBeVisible()
    await expect(recovered.getByLabel('1 students', { exact: true })).toBeVisible()
    await recovered.getByRole('button', { name: 'End class', exact: true }).click()
    await expect(recovered.getByRole('heading', { name: 'Review remains open' })).toBeVisible()
    await recovered.getByRole('button', { name: 'Revoke review access', exact: true }).click()
    await student.goto(inviteUrl)
    await expect(student.getByRole('heading', { name: 'Open teaching slides' })).toBeVisible()
  } finally {
    await recovered.close()
    await studentContext.close()
  }
  await page.goto('/admin')
  await page.getByRole('button', { name: `More actions for ${slideName}`, exact: true }).click()
}
