import { expect, test, type Page } from './qa-test'
import { execFileSync } from 'node:child_process'
import { appendFileSync, mkdirSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { signIn } from '../e2e-live/capacity-helpers'

function cpuGate(percent: number, prior85: number) {
  const consecutive85 = percent >= 85 ? prior85 + 1 : 0
  return { consecutive85, stop: percent >= 90 || consecutive85 >= 2 }
}

test('stress CPU gate stops sustained saturation', () => {
  expect(cpuGate(90, 0).stop).toBe(true)
  expect(cpuGate(85, 0)).toEqual({ consecutive85: 1, stop: false })
  expect(cpuGate(85, 1).stop).toBe(true)
  expect(cpuGate(84, 1)).toEqual({ consecutive85: 0, stop: false })
})

// All targets and credentials are generated by the disposable stack launcher.
test('isolated library sizes and bounded concurrent browser soak', async ({ browser }) => {
  test.skip(process.env.PATHLAB_E2E_STRESS !== '1', 'Opt in with run_fullstack_tests.py --stress')
  test.setTimeout(60 * 60_000)
  const baseURL = process.env.PATHLAB_E2E_BASE_URL!
  expect(new URL(baseURL).hostname).toBe('127.0.0.1')
  const output = process.env.PATHLAB_E2E_REPORT_DIR
  if (!output) throw new Error('--report-dir is required for stress evidence')
  mkdirSync(output, { recursive: true })
  const receipt = (value: object) => appendFileSync(path.join(output, 'stress.jsonl'),
    JSON.stringify({ at: new Date().toISOString(), ...value }) + '\n')
  const owner = await browser.newContext({ baseURL })
  const page = await owner.newPage()
  try {
    await signIn(page, process.env.PATHLAB_E2E_USERNAME!, process.env.PATHLAB_E2E_PASSWORD!)
    for (const count of [0, 1, 100, 1000]) {
      execFileSync(process.env.PATHLAB_E2E_PYTHON!,
        [path.resolve('../../scripts/seed_frontend_qa.py'), String(count)], { stdio: 'pipe' })
      const response = await owner.request.get('/api/v2/admin/library/items?q=Frontend%20QA')
      expect(response.ok()).toBe(true)
      expect((await response.json()).total).toBe(count)
      await page.goto('/admin?q=Frontend%20QA')
      if (count === 0) await expect(page.getByRole('heading', { name: 'No slides here' })).toBeVisible()
      else await expect(page.getByRole('heading', { name: /^Frontend QA \d{4}$/ }).first()).toBeVisible()
      receipt({ phase: 'fixture-size', count, status: 'passed', metadataOnly: true })
    }
    const state = await owner.storageState()
    let stopped = false
    let highestStable = 0
    let previousCpu = os.cpus().map((cpu) => cpu.times)
    for (const [sessions, duration] of [[1, 300_000], [5, 300_000], [10, 300_000], [20, 300_000], [20, 1_800_000]]) {
      if (stopped) break
      if (duration === 1_800_000 && highestStable !== sessions) break
      const contexts = []
      let badWindows = 0
      let cpu85Windows = 0
      let requests = 0
      let errors = 0
      const latencies: number[] = []
      const setupStarted = Date.now()
      const pages: Page[] = []
      try {
        for (let index = 0; index < sessions; index++) {
          if (os.freemem() < 1024 ** 3) throw new Error('Resource gate: less than 1 GiB free RAM')
          const context = await browser.newContext({ baseURL, storageState: state })
          contexts.push(context)
          const client = await context.newPage()
          client.on('pageerror', (error) => {
            errors++; stopped = true
            receipt({ phase: 'page-error', sessions, client: index, error: error.message.slice(0, 1000) })
          })
          await client.goto('/admin?q=Frontend%20QA')
          pages.push(client)
        }
        const started = Date.now()
        const until = started + duration
        receipt({ phase: 'started', sessions, durationMs: duration, setupMs: started - setupStarted })
        let lastWindow = Date.now()
        let lastRequests = 0
        let lastErrors = 0
        let iteration = 0
        while (Date.now() < until && !stopped) {
          await Promise.all(pages.map(async (client, index) => {
            const tick = Date.now()
            requests++
            try {
              const query = `Frontend QA ${String((iteration + index) % 1000).padStart(4, '0')}`
              const response = client.waitForResponse((item) => {
                const url = new URL(item.url())
                return url.pathname === '/api/v2/admin/library/items' && url.searchParams.get('q') === query
              })
              await client.getByRole('searchbox', { name: 'Search slides', exact: true }).fill(query)
              expect((await response).ok()).toBe(true)
              await expect(client.getByRole('heading', { name: query, exact: true })).toBeVisible()
              if (index % 2 === 0) await client.getByRole('button', { name: 'Filters', exact: true }).click()
            } catch (error) {
              errors++
              receipt({ phase: 'action-error', sessions, client: index, iteration,
                error: error instanceof Error ? error.message.slice(0, 1000) : String(error) })
            }
            latencies.push(Date.now() - tick)
          }))
          iteration++
          if (Date.now() - lastWindow >= 30_000) {
            const errorRate = (errors - lastErrors) / Math.max(1, requests - lastRequests)
            badWindows = errorRate > 0.01 ? badWindows + 1 : 0
            const health = await owner.request.get('/readyz')
            const currentCpu = os.cpus().map((cpu) => cpu.times)
            let idle = 0, total = 0
            currentCpu.forEach((cpu, index) => {
              idle += cpu.idle - previousCpu[index].idle
              total += Object.values(cpu).reduce((a, b) => a + b, 0)
                - Object.values(previousCpu[index]).reduce((a, b) => a + b, 0)
            })
            previousCpu = currentCpu
            const systemCpuPercent = total ? 100 * (1 - idle / total) : 0
            const cpu = cpuGate(systemCpuPercent, cpu85Windows)
            cpu85Windows = cpu.consecutive85
            const sorted = [...latencies].sort((a, b) => a - b)
            receipt({ phase: 'running', sessions, elapsedMs: Date.now() - started, requests, errors,
              errorRate, freeBytes: os.freemem(), systemCpuPercent,
              p50Ms: sorted[Math.floor(sorted.length * .5)], p95Ms: sorted[Math.floor(sorted.length * .95)],
              p99Ms: sorted[Math.floor(sorted.length * .99)], healthy: health.ok() })
            if (cpu.stop) receipt({ phase: 'resource-stop', sessions, reason: 'host CPU saturation', systemCpuPercent })
            stopped = stopped || cpu.stop || badWindows >= 2 || !health.ok() || os.freemem() < 1024 ** 3
            lastWindow = Date.now(); lastRequests = requests; lastErrors = errors
          }
          await new Promise((resolve) => setTimeout(resolve, 2000))
        }
        const sorted = [...latencies].sort((a, b) => a - b)
        receipt({ phase: stopped ? 'stopped' : 'completed', sessions,
          durationMs: Date.now() - started, requests, errors,
          p50Ms: sorted[Math.floor(sorted.length * .5)], p95Ms: sorted[Math.floor(sorted.length * .95)],
          p99Ms: sorted[Math.floor(sorted.length * .99)] })
        if (!stopped && errors / Math.max(requests, 1) <= .01) highestStable = sessions
        else stopped = true
      } finally { await Promise.all(contexts.map((context) => context.close())) }
    }
    const recovery = await owner.request.get('/readyz')
    const inventory = await owner.request.get('/api/v2/admin/library/items?q=Frontend%20QA')
    expect(recovery.ok()).toBe(true)
    expect((await inventory.json()).total).toBe(1000)
    receipt({ phase: 'recovery', healthy: true, fixtureCount: 1000, highestStable, stopped })
    expect(stopped, 'Campaign stopped at a safety gate; inspect stress.jsonl').toBe(false)
  } finally { await owner.close() }
})
