import { expect, test } from './qa-test'
import { fault } from './fixture-faults'
import { signIn, uploadSyntheticSlide, waitForSlideConversion } from '../e2e-live/capacity-helpers'

test('metadata, filters, folder share rotation, trash and restore persist', async ({ page, browser }, testInfo) => {
  await signIn(page, process.env.PATHLAB_E2E_USERNAME!, process.env.PATHLAB_E2E_PASSWORD!)
  const name = 'QA metadata lifecycle'
  const id = await uploadSyntheticSlide(page, process.env.PATHLAB_E2E_OME!, name)
  await waitForSlideConversion(page, id)
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  for (const width of [320, 360, 390, 600, 601, 768, 900, 901, 1250, 1251, 1440, 1920]) {
    await page.setViewportSize({ width, height: width <= 600 ? 844 : 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 390 || width === 1440) {
      for (const theme of ['Light', 'Dark']) {
        await page.getByRole('radio', { name: theme, exact: true }).check()
        await page.screenshot({ path: testInfo.outputPath(`library-${width}-${theme}.png`) })
      }
    }
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('radio', { name: 'Light', exact: true }).check()
  const menu = () => page.getByRole('button', { name: `More actions for ${name}`, exact: true }).click()
  const slideMenuButton = page.getByRole('button', { name: `More actions for ${name}`, exact: true })
  await menu()
  const privateMenuItems = (await page.getByRole('menu').getByRole('menuitem').allTextContents())
    .map((item) => item.trim().replace(/\s+/g, ' ')).sort()
  expect(privateMenuItems).toEqual([
    'Add to collection', 'Details', 'Edit details', 'Move', 'Move to Trash', 'Preview', 'Publish',
  ])
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).toBeHidden()
  await expect(slideMenuButton).toBeFocused()
  await menu()
  await page.getByRole('menuitem', { name: 'Details', exact: true }).click()
  const initialDetails = page.getByRole('complementary', { name: 'Slide details', exact: true })
  await expect(initialDetails).toBeVisible()
  await initialDetails.getByRole('button', { name: 'Close slide details', exact: true }).click()
  await menu()
  await page.getByRole('menuitem', { name: 'Edit details', exact: true }).click()
  const edit = page.getByRole('dialog', { name: 'Edit slide details', exact: true })
  for (const [label, value] of [['Description', 'Synthetic metadata'], ['Case ID', 'QA-CASE'],
    ['Organ / site', 'QA organ'], ['Stain', 'QA stain'], ['Diagnosis', 'QA diagnosis'],
    ['Course', 'QA course'], ['Tags (comma separated)', 'qa-tag'], ['Teaching note', 'QA teaching'],
    ['Administrator note', 'Private synthetic note']]) {
    await edit.getByRole('textbox', { name: label, exact: true }).fill(value)
  }
  await edit.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(edit).not.toBeVisible()
  await page.reload()
  await menu()
  await page.getByRole('menuitem', { name: 'Edit details', exact: true }).click()
  await expect(edit.getByRole('textbox', { name: 'Administrator note', exact: true })).toHaveValue('Private synthetic note')
  await edit.getByRole('button', { name: 'Close Edit slide details', exact: true }).click()
  const detailsPanel = page.getByRole('complementary', { name: 'Slide details', exact: true })
  await detailsPanel.getByRole('button', { name: 'Close slide details', exact: true }).click()
  await expect(detailsPanel).not.toBeVisible()
  const slideCard = page.getByRole('article', { name, exact: true })
  await slideCard.getByRole('button', { name: 'Quick look', exact: true }).click()
  const quickLook = page.getByRole('dialog', { name: `Quick look: ${name}`, exact: true })
  const quickLookRotation = page.getByRole('dialog', { name: 'Slide rotation', exact: true })
  await quickLook.getByRole('button', { name: /Open rotation controls/ }).click()
  await quickLookRotation.getByRole('button', { name: 'Rotate to 90 degrees', exact: true }).click()
  await expect(quickLookRotation.getByRole('slider', { name: 'Rotation dial', exact: true })).toHaveAttribute('aria-valuenow', '90')
  await quickLookRotation.getByRole('button', { name: 'Rotate to 0 degrees', exact: true }).click()
  await page.keyboard.press('Escape')
  await expect(quickLookRotation).toBeHidden()
  await expect(quickLook).toBeVisible()
  await quickLook.getByRole('button', { name: 'Open viewer', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`/admin/preview/${id}$`))
  await page.goto('/admin')
  const openCommands = () => page.getByRole('button', { name: 'Search commands Ctrl / ⌘ K', exact: true }).click()
  const commandDialog = page.getByRole('dialog', { name: 'Search library commands', exact: true })
  const commandSearch = commandDialog.getByRole('textbox', { name: 'Slide name, organ, stain, case, or action', exact: true })
  await openCommands()
  await expect(commandSearch).toBeFocused()
  await commandSearch.fill('no matching command')
  await expect(commandDialog.getByRole('status')).toHaveText('No matching commands in this library view.')
  await commandSearch.fill('Upload slides')
  await commandDialog.getByRole('button', { name: /Upload slides/ }).click()
  const uploadDialog = page.getByRole('dialog', { name: 'Upload OME-TIFF', exact: true })
  await expect(uploadDialog).toBeVisible()
  await uploadDialog.getByRole('button', { name: 'Close Upload OME-TIFF', exact: true }).click()
  await openCommands()
  await commandSearch.fill('New folder')
  await commandDialog.getByRole('button', { name: /New folder/ }).click()
  const commandFolderDialog = page.getByRole('dialog', { name: 'New folder', exact: true })
  const commandFolder = `QA command folder ${Date.now().toString(36)}`
  await commandFolderDialog.getByRole('textbox', { name: 'Name', exact: true }).fill(commandFolder)
  await commandFolderDialog.getByRole('button', { name: 'Create', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: 'Slide library', exact: true }).click()
  await expect(page.getByRole('treeitem', { name: commandFolder, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close library navigator', exact: true }).click()
  await openCommands()
  await commandSearch.fill('Open Classroom')
  const classroomFoldersLoaded = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/v1/admin/classroom/setup/folders')
  const classroomsLoaded = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/v1/admin/classroom/sessions')
  await commandDialog.getByRole('button', { name: /Open Classroom/ }).click()
  expect((await classroomFoldersLoaded).status()).toBe(200)
  expect((await classroomsLoaded).status()).toBe(200)
  await expect(page.getByRole('heading', { name: 'Choose a class folder', exact: true })).toBeVisible()
  await expect(page.getByText('Loading class folders…', { exact: true })).toBeHidden()
  await page.goto('/admin')
  await openCommands()
  await commandSearch.fill('Open Study Coach')
  const studyPacksLoaded = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/v1/admin/study/packs')
  const studyCoursesLoaded = page.waitForResponse((response) => new URL(response.url()).pathname === '/api/v1/admin/study/courses')
  await commandDialog.getByRole('button', { name: /Open Study Coach/ }).click()
  expect((await studyPacksLoaded).status()).toBe(200)
  expect((await studyCoursesLoaded).status()).toBe(200)
  await expect(page.getByRole('heading', { name: 'Study Coach', exact: true })).toBeVisible()
  await expect(page.getByText('Loading Study Coach…', { exact: true })).toBeHidden()
  await page.goto('/admin')
  await openCommands()
  await commandSearch.fill(name)
  await commandDialog.getByRole('button', { name: new RegExp(name) }).click()
  await expect(page).toHaveURL(new RegExp(`/admin/preview/${id}$`))
  await page.goto('/admin?location=trash')
  await openCommands()
  await expect(commandDialog.getByRole('button', { name: new RegExp(name) })).toHaveCount(0)
  await commandDialog.getByRole('button', { name: 'Close Search library commands', exact: true }).click()
  await page.goto('/admin')
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  for (const [label, value] of [['Organ / site', 'QA organ'], ['Stain', 'QA stain'],
    ['Diagnosis', 'QA diagnosis'], ['Course', 'QA course'], ['Processing state', 'ready_private']]) {
    await page.getByRole('combobox', { name: label, exact: true }).selectOption(value)
  }
  await page.getByRole('textbox', { name: 'Tag', exact: true }).fill('qa-tag')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await expect(page).toHaveURL(/qa-tag/)
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await page.getByRole('button', { name: 'Close filters', exact: true }).click()

  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByRole('menuitem', { name: 'New folder', exact: true }).click()
  const folder = page.getByRole('dialog', { name: 'New folder', exact: true })
  await folder.getByLabel('Name', { exact: true }).fill('QA shared folder')
  await folder.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(folder).not.toBeVisible()
  await menu()
  await page.getByRole('menuitem', { name: 'Move', exact: true }).click()
  const move = page.getByRole('dialog', { name: 'Move slides', exact: true })
  await move.getByRole('combobox', { name: 'Destination', exact: true }).selectOption({ label: 'QA shared folder' })
  await move.getByRole('button', { name: 'Move', exact: true }).click()
  await expect(move).not.toBeVisible()
  await page.getByRole('button', { name: 'Slide library', exact: true }).click()
  await page.locator('#library-navigator').getByText('QA shared folder', { exact: true }).first().click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  const share = page.getByRole('dialog', { name: 'Share QA shared folder', exact: true })
  await share.locator('label').filter({ hasText: 'I confirm public names' }).click()
  await expect(share.getByRole('checkbox', { name: /I confirm public names/ })).toBeChecked()
  await share.getByRole('button', { name: 'Create shared link', exact: true }).click()
  const link = share.getByRole('textbox', { name: 'Shared link', exact: true })
  await expect(link).toBeVisible()
  const previous = await link.inputValue()
  const anonymous = await browser.newContext()
  try {
    const viewer = await anonymous.newPage()
    await viewer.goto(previous)
    await expect(viewer.getByRole('heading', { name, exact: true })).toBeVisible()
    await share.getByRole('button', { name: 'Rotate', exact: true }).click()
    await expect(link).not.toHaveValue(previous)
    const current = await link.inputValue()
    const oldId = new URL(previous).pathname.split('/').pop()
    expect((await page.request.get(`/api/v2/public/folders/${oldId}`)).status()).toBe(404)
    await viewer.goto(current)
    await expect(viewer.getByRole('heading', { name, exact: true })).toBeVisible()
    fault('expire-share', new URL(current).pathname.split('/').pop())
    await viewer.reload()
    await expect(viewer.getByRole('heading', { name: 'This shared library is unavailable', exact: true })).toBeVisible()
    await share.getByRole('button', { name: 'Revoke', exact: true }).click()
    await share.getByRole('button', { name: 'Confirm revoke', exact: true }).click()
    await expect(share.getByText('Shared link revoked.', { exact: true })).toBeVisible()
    const currentId = new URL(current).pathname.split('/').pop()
    expect((await page.request.get(`/api/v2/public/folders/${currentId}`)).status()).toBe(404)
  } finally { await anonymous.close() }
  await share.getByRole('button', { name: 'Close Share QA shared folder', exact: true }).click()
  await menu()
  await page.getByRole('menuitem', { name: 'Move to Trash', exact: true }).click()
  await page.goto('/admin?location=trash')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await menu()
  const trashedMenuItems = (await page.getByRole('menu').getByRole('menuitem').allTextContents())
    .map((item) => item.trim().replace(/\s+/g, ' ')).sort()
  expect(trashedMenuItems).toEqual(['Delete permanently', 'Details', 'Restore'])
  await page.getByRole('menuitem', { name: 'Delete permanently', exact: true }).click()
  const slideDelete = page.getByRole('dialog', { name: 'Delete permanently', exact: true })
  await expect(slideDelete).toBeVisible()
  await slideDelete.getByRole('button', { name: 'Close Delete permanently', exact: true }).click()
  await expect(slideDelete).not.toBeVisible()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await menu()
  await page.getByRole('menuitem', { name: 'Restore', exact: true }).click()
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByRole('menuitem', { name: 'New collection', exact: true }).click()
  const collection = page.getByRole('dialog', { name: 'New collection', exact: true })
  await collection.getByLabel('Name', { exact: true }).fill('QA bulk collection')
  await collection.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(collection).not.toBeVisible()
  await menu()
  await page.getByRole('menuitem', { name: 'Add to collection', exact: true }).click()
  const singleCollection = page.getByRole('dialog', { name: 'Add to collection', exact: true })
  await singleCollection.getByRole('combobox', { name: 'Collection', exact: true }).selectOption({ label: 'QA bulk collection' })
  await singleCollection.getByRole('button', { name: 'Add slides', exact: true }).click()
  await expect(singleCollection).not.toBeVisible()

  const secondName = 'QA collection second slide'
  const secondId = await uploadSyntheticSlide(page, process.env.PATHLAB_E2E_OME!, secondName)
  await waitForSlideConversion(page, secondId)
  await page.reload()
  await page.getByRole('checkbox', { name: `Select ${secondName}`, exact: true }).press('Space')
  await page.getByRole('toolbar', { name: 'Selection actions' }).getByRole('button', { name: 'Add to collection', exact: true }).click()
  const addSecond = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Add to collection', exact: true }) })
  await addSecond.getByRole('combobox', { name: 'Collection', exact: true }).selectOption({ label: 'QA bulk collection' })
  await addSecond.getByRole('button', { name: 'Add slides', exact: true }).click()
  await expect(addSecond).not.toBeVisible()

  await page.getByRole('button', { name: 'Slide library', exact: true }).click()
  const collectionNavigator = page.locator('#library-navigator')
  await collectionNavigator.locator('.navigator-list-row').filter({ hasText: 'QA bulk collection' })
    .getByRole('button').first().click()
  await expect(page.getByRole('heading', { name: 'QA bulk collection', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  const collectionShare = page.getByRole('dialog', { name: 'Share QA bulk collection', exact: true })
  await expect(collectionShare.getByText('2 slides ready for review', { exact: true })).toBeVisible()
  await collectionShare.locator('label').filter({ hasText: 'I confirm public names' }).click()
  await expect(collectionShare.getByRole('checkbox', { name: /I confirm public names/ })).toBeChecked()
  await collectionShare.getByRole('button', { name: 'Create shared link', exact: true }).click()
  const collectionLink = collectionShare.getByRole('textbox', { name: 'Shared link', exact: true })
  await expect(collectionLink).toHaveValue(/\/c\/[^/]+$/)
  const collectionPublicUrl = await collectionLink.inputValue()
  const collectionViewerContext = await browser.newContext()
  try {
    const collectionViewer = await collectionViewerContext.newPage()
    await collectionViewer.setViewportSize({ width: 390, height: 844 })
    await collectionViewer.goto(collectionPublicUrl)
    await expect(collectionViewer.getByRole('heading', { level: 1, name: 'QA bulk collection', exact: true })).toBeVisible()
    const slideCaption = collectionViewer.locator('.shared-slide-caption h2')
    await expect(slideCaption).toHaveText(new RegExp(`^(?:${name}|${secondName})$`))
    await expect(collectionViewer.locator('.openseadragon-canvas canvas').first()).toBeVisible()
    for (const theme of ['Dark', 'System', 'Light']) {
      const preference = collectionViewer.getByRole('radio', { name: theme, exact: true })
      await preference.check()
      await expect(preference).toBeChecked()
    }
    const loadingMode = collectionViewer.getByRole('combobox', { name: 'Loading mode', exact: true })
    for (const mode of ['data-saver', 'full', 'auto']) {
      await loadingMode.selectOption(mode)
      await expect(loadingMode).toHaveValue(mode)
    }
    const sharedTools = collectionViewer.getByRole('navigation', { name: 'Shared viewer controls', exact: true })
    await expect(sharedTools.getByRole('button', { name: 'Previous slide', exact: true })).toBeDisabled()
    const nextSlide = sharedTools.getByRole('button', { name: 'Next slide', exact: true })
    const previousSlide = sharedTools.getByRole('button', { name: 'Previous slide', exact: true })
    await expect(nextSlide).toBeEnabled()
    const positionLabel = collectionViewer.locator('.shared-viewer-header > span')
    const firstSlideName = await slideCaption.innerText()
    await expect(positionLabel).toHaveText('1 / 2')
    const secondSlideDescriptor = collectionViewer.waitForResponse((response) => {
      const { pathname } = new URL(response.url())
      return pathname.endsWith('/slides/1/tiles/slide.dzi')
    })
    const secondSlideTile = collectionViewer.waitForResponse((response) => {
      const { pathname } = new URL(response.url())
      return pathname.includes('/slides/1/tiles/') && /\.(?:jpe?g)$/i.test(pathname)
    })
    await nextSlide.click()
    expect((await secondSlideDescriptor).status()).toBe(200)
    expect((await secondSlideTile).status()).toBe(200)
    await expect(positionLabel).toHaveText('2 / 2')
    await expect(nextSlide).toBeDisabled()
    const secondSlideName = await slideCaption.innerText()
    expect(secondSlideName).not.toBe(firstSlideName)
    await collectionViewer.reload()
    await expect(slideCaption).toHaveText(secondSlideName)
    await expect(positionLabel).toHaveText('2 / 2')
    await expect(nextSlide).toBeDisabled()
    await expect(collectionViewer.getByRole('radio', { name: 'Light', exact: true })).toBeChecked()
    await expect(loadingMode).toHaveValue('auto')
    await previousSlide.click()
    await expect(slideCaption).toHaveText(firstSlideName)
    await expect(positionLabel).toHaveText('1 / 2')
    await expect(previousSlide).toBeDisabled()
    await expect(nextSlide).toBeEnabled()
    const navigatorTrigger = collectionViewer.getByRole('button', { name: 'Open slide navigator', exact: true })
    await navigatorTrigger.click()
    await expect(navigatorTrigger).toHaveAttribute('aria-expanded', 'true')
    const sharedSearch = collectionViewer.getByRole('searchbox', { name: 'Search shared slides', exact: true })
    const sharedSlides = collectionViewer.getByRole('complementary', { name: 'Shared slides', exact: true })
    await expect(sharedSearch).toBeVisible()
    await expect.poll(() => sharedSlides.evaluate((element) => Math.round(element.getBoundingClientRect().left))).toBe(0)
    await testInfo.attach('collection-viewer-mobile-navigator-open.png', {
      contentType: 'image/png', body: await collectionViewer.screenshot(),
    })
    await sharedSearch.fill('No matching synthetic slide')
    await expect(sharedSlides.locator('.share-slide-list button')).toHaveCount(0)
    await sharedSearch.fill(name)
    const selectedSlide = sharedSlides.getByRole('button', { name: new RegExp(name) })
    await selectedSlide.click()
    await expect(selectedSlide).toHaveClass(/active/)
    await expect(slideCaption).toHaveText(name)
    await expect(navigatorTrigger).toHaveAttribute('aria-expanded', 'false')
    await expect(sharedSearch).toBeHidden()
    await expect(navigatorTrigger).toBeFocused()
    await navigatorTrigger.click()
    await expect(navigatorTrigger).toHaveAttribute('aria-expanded', 'true')
    await expect(sharedSearch).toBeVisible()
    await sharedSlides.getByRole('button', { name: 'Close slide navigator', exact: true }).click()
    await expect(navigatorTrigger).toHaveAttribute('aria-expanded', 'false')
    await expect(sharedSearch).toBeHidden()
    await expect(navigatorTrigger).toBeFocused()
    await navigatorTrigger.click()
    await collectionViewer.locator('.share-drawer-backdrop').click({ position: { x: 380, y: 200 } })
    await expect(navigatorTrigger).toHaveAttribute('aria-expanded', 'false')
    await expect(sharedSearch).toBeHidden()
    await expect(navigatorTrigger).toBeFocused()
    await testInfo.attach('collection-viewer-mobile-navigator-closed.png', {
      contentType: 'image/png', body: await collectionViewer.screenshot(),
    })
    await navigatorTrigger.click()
    await collectionViewer.keyboard.press('Escape')
    await expect(navigatorTrigger).toHaveAttribute('aria-expanded', 'false')
    await expect(sharedSearch).toBeHidden()
    await expect(navigatorTrigger).toBeFocused()
    const viewerCanvas = collectionViewer.locator('.openseadragon-canvas canvas').first()
    await expect(collectionViewer.locator('.viewer-poster')).toHaveCount(0)
    const homeView = await viewerCanvas.screenshot()
    await sharedTools.getByRole('button', { name: 'Zoom in', exact: true }).click()
    await expect.poll(async () => !Buffer.from(await viewerCanvas.screenshot()).equals(Buffer.from(homeView))).toBe(true)
    const zoomedView = await viewerCanvas.screenshot()
    await sharedTools.getByRole('button', { name: 'Home view', exact: true }).click()
    await expect.poll(async () => !Buffer.from(await viewerCanvas.screenshot()).equals(Buffer.from(zoomedView))).toBe(true)
    const homeResult = await viewerCanvas.screenshot()
    await sharedTools.getByRole('button', { name: 'Zoom in', exact: true }).click()
    await expect.poll(async () => !Buffer.from(await viewerCanvas.screenshot()).equals(Buffer.from(homeResult))).toBe(true)
    const zoomedAgain = await viewerCanvas.screenshot()
    await sharedTools.getByRole('button', { name: 'Zoom out', exact: true }).click()
    await expect.poll(async () => !Buffer.from(await viewerCanvas.screenshot()).equals(Buffer.from(zoomedAgain))).toBe(true)
    const rotationTrigger = collectionViewer.getByRole('button', { name: /Open rotation controls/ })
    await rotationTrigger.click()
    const rotationDialog = collectionViewer.getByRole('dialog', { name: 'Slide rotation', exact: true })
    const rotationDial = rotationDialog.getByRole('slider', { name: 'Rotation dial', exact: true })
    await expect(rotationDial).toHaveAttribute('aria-valuenow', '0')
    for (const degrees of [90, 180, 270, 0]) {
      await rotationDialog.getByRole('button', { name: `Rotate to ${degrees} degrees`, exact: true }).click()
      await expect(rotationDial).toHaveAttribute('aria-valuenow', String(degrees))
    }
    await rotationDial.focus()
    await collectionViewer.keyboard.press('ArrowRight')
    await expect(rotationDial).toHaveAttribute('aria-valuenow', '1')
    await collectionViewer.keyboard.press('ArrowLeft')
    await expect(rotationDial).toHaveAttribute('aria-valuenow', '0')
    const dialBounds = await rotationDial.boundingBox()
    if (!dialBounds) throw new Error('Rotation dial has no rendered bounds')
    await collectionViewer.mouse.move(dialBounds.x + dialBounds.width * 0.75, dialBounds.y + dialBounds.height * 0.25)
    await collectionViewer.mouse.down()
    await collectionViewer.mouse.move(dialBounds.x + dialBounds.width * 0.9, dialBounds.y + dialBounds.height / 2)
    await collectionViewer.mouse.up()
    await expect.poll(() => rotationDial.getAttribute('aria-valuenow').then(Number)).toBeGreaterThanOrEqual(89)
    await expect.poll(() => rotationDial.getAttribute('aria-valuenow').then(Number)).toBeLessThanOrEqual(91)
    await rotationDial.press('Home')
    await expect(rotationDial).toHaveAttribute('aria-valuenow', '0')
    await rotationTrigger.click()
    await expect(rotationDialog).toBeHidden()
    await rotationTrigger.click()
    await collectionViewer.getByRole('heading', { level: 1, name: 'QA bulk collection', exact: true }).click()
    await expect(rotationDialog).toBeHidden()
    await rotationTrigger.click()
    await expect(rotationDialog).toBeVisible()
    await collectionViewer.keyboard.press('Escape')
    await expect(rotationDialog).toBeHidden()
    await sharedTools.getByRole('button', { name: 'Fullscreen', exact: true }).click()
    await expect.poll(() => collectionViewer.evaluate(() => Boolean(document.fullscreenElement))).toBe(true)
    await collectionViewer.keyboard.press('Escape')
    await expect.poll(() => collectionViewer.evaluate(() => Boolean(document.fullscreenElement))).toBe(false)
    await testInfo.attach('collection-shared-route-controls.json', {
      contentType: 'application/json',
      body: JSON.stringify({ route: new URL(collectionPublicUrl).pathname, explored: [
        'Theme Light, Dark, System', 'Loading Auto, Data saver, Full detail', 'Previous and Next slide',
        'Reload retains selected slide', 'Open slide navigator', 'Search shared slides', 'Select slide',
        'Empty and matching search results', 'Close navigator by button, backdrop and Escape with focus return',
        'Zoom in/out and Home view each change the rendered canvas', 'Fullscreen and Escape',
        'Rotation cardinal buttons, slider keyboard and pointer drag, button/outside/Escape dismissal',
      ] }),
    })
    await collectionShare.getByRole('button', { name: 'Revoke', exact: true }).click()
    await collectionShare.getByRole('button', { name: 'Confirm revoke', exact: true }).click()
    await expect(collectionShare.getByText('Shared link revoked.', { exact: true })).toBeVisible()
    await collectionViewer.reload()
    await expect(collectionViewer.getByRole('heading', { name: 'This shared library is unavailable', exact: true })).toBeVisible()
    await collectionViewer.getByRole('button', { name: 'Try again', exact: true }).click()
    await expect(collectionViewer.getByRole('heading', { name: 'This shared library is unavailable', exact: true })).toBeVisible()
  } finally { await collectionViewerContext.close() }
  await collectionShare.getByRole('button', { name: 'Close Share QA bulk collection', exact: true }).click()
  await page.goto('/admin')

  await page.getByRole('checkbox', { name: `Select ${name}`, exact: true }).press('Space')
  await expect(page.getByRole('checkbox', { name: `Select ${name}`, exact: true })).toBeChecked()
  await page.getByRole('toolbar', { name: 'Selection actions' }).getByRole('button', { name: 'Edit tags', exact: true }).click()
  const tags = page.getByRole('dialog', { name: 'Edit tags', exact: true })
  await tags.getByLabel('Tags', { exact: true }).fill('QA bulk tag, QA second tag')
  await tags.getByRole('button', { name: 'Save tags', exact: true }).click()
  await expect(tags).not.toBeVisible()
  await page.reload()
  await expect(page.getByText('QA bulk tag', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: `Select ${name}`, exact: true }).press('Space')
  await expect(page.getByRole('checkbox', { name: `Select ${name}`, exact: true })).toBeChecked()
  await page.getByRole('toolbar', { name: 'Selection actions' }).getByRole('button', { name: 'Add to collection', exact: true }).click()
  const add = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Add to collection', exact: true }) })
  await testInfo.attach('collection-dialog-accessibility', { contentType: 'application/json', body: JSON.stringify(await add.evaluate((element) => ({
    label: element.getAttribute('aria-labelledby'),
    heading: element.querySelector('h2')?.outerHTML,
    labelMatches: document.querySelectorAll(`[id="${element.getAttribute('aria-labelledby')}"]`).length,
  }))) })
  await expect(add).toHaveAccessibleName('Add to collection')
  await add.getByRole('combobox', { name: 'Collection', exact: true }).selectOption({ label: 'QA bulk collection' })
  await add.getByRole('button', { name: 'Add slides', exact: true }).click()
  await expect(add).not.toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: `Open details for ${name}`, exact: true }).click()
  await expect(page.getByRole('complementary', { name: 'Slide details' }).getByText('QA bulk collection', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close slide details', exact: true }).click()
  await page.getByRole('button', { name: /^Open storage,/ }).click()
  await page.getByRole('searchbox', { name: 'Search stored files', exact: true }).fill(name)
  await expect(page.getByRole('row').filter({ hasText: name })).toHaveCount(1)
  await page.getByRole('button', { name: `Move to Trash: ${name}`, exact: true }).click()
  await expect(page.getByRole('button', { name: `Restore: ${name}`, exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: `Restore: ${name}`, exact: true }).click()
  await expect(page.getByRole('button', { name: `Move to Trash: ${name}`, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to slide library', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()

  await menu()
  await page.getByRole('menuitem', { name: 'Move to Trash', exact: true }).click()
  await page.goto('/admin?location=trash')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await menu()
  await page.getByRole('menuitem', { name: 'Delete permanently', exact: true }).click()
  const menuDelete = page.getByRole('dialog', { name: 'Delete permanently', exact: true })
  await expect(menuDelete).toBeVisible()
  const menuDeletion = page.waitForResponse((response) => response.request().method() === 'DELETE'
    && new URL(response.url()).pathname === `/api/v2/admin/slides/${id}`)
  await menuDelete.getByRole('button', { name: 'Delete permanently', exact: true }).click()
  expect((await menuDeletion).status()).toBe(202)
  await expect(menuDelete).not.toBeVisible()
  await expect(page.getByRole('heading', { name, exact: true })).not.toBeVisible()

  await page.goto('/admin')
  const storageName = 'QA storage permanent deletion'
  const storageId = await uploadSyntheticSlide(page, process.env.PATHLAB_E2E_OME!, storageName)
  await waitForSlideConversion(page, storageId)
  await page.reload()
  await expect(page.getByRole('heading', { name: storageName, exact: true })).toBeVisible()
  await page.getByRole('button', { name: /^Open storage,/ }).click()
  const storageSearch = page.getByRole('searchbox', { name: 'Search stored files', exact: true })
  await storageSearch.fill(storageName)
  const storageRow = page.getByRole('row').filter({ hasText: storageName })
  await expect(storageRow).toHaveCount(1)
  await page.getByRole('button', { name: `Move to Trash: ${storageName}`, exact: true }).click()
  await page.getByRole('button', { name: `Delete permanently: ${storageName}`, exact: true }).click()
  const storageDelete = page.getByRole('dialog', { name: 'Delete permanently?', exact: true })
  await expect(storageDelete).toBeVisible()
  await storageDelete.getByRole('button', { name: 'Keep file', exact: true }).click()
  await expect(storageDelete).not.toBeVisible()
  await expect(storageRow).toHaveCount(1)
  await page.getByRole('button', { name: `Delete permanently: ${storageName}`, exact: true }).click()
  const storageDeletion = page.waitForResponse((response) => response.request().method() === 'DELETE'
    && new URL(response.url()).pathname === `/api/v2/admin/slides/${storageId}`)
  await storageDelete.getByRole('button', { name: 'Delete permanently', exact: true }).click()
  expect((await storageDeletion).status()).toBe(202)
  await expect(page.getByRole('status').filter({ hasText: `${storageName} is queued for permanent deletion.` })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Storage', exact: true })).toBeVisible()
  await storageSearch.fill(storageName)
  await expect.poll(async () => {
    if (!(await storageRow.count())) return 'removed'
    return (await storageRow.innerText()).includes('Deleting') ? 'deleting' : 'still present'
  }).toMatch(/^(removed|deleting)$/)

  await testInfo.attach('library-permanent-deletion.json', {
    body: JSON.stringify({ slideMenu: { status: 202, confirmed: true }, storage: { status: 202, confirmed: true } }, null, 2),
    contentType: 'application/json',
  })
})
