import { expect, test } from './qa-test'
import { fault } from './fixture-faults'
import { signIn, uploadSyntheticSlide, waitForSlideConversion } from '../e2e-live/capacity-helpers'

test('metadata, filters, folder share rotation, trash and restore persist', async ({ page, browser }, testInfo) => {
  await signIn(page, process.env.PATHLAB_E2E_USERNAME!, process.env.PATHLAB_E2E_PASSWORD!)
  const name = 'QA metadata lifecycle'
  const id = await uploadSyntheticSlide(page, process.env.PATHLAB_E2E_OME!, name)
  await waitForSlideConversion(page, id)
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  for (const width of [320, 360, 390, 600, 601, 768, 900, 901, 1250, 1251, 1440, 1920]) {
    await page.setViewportSize({ width, height: width <= 600 ? 844 : 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    if (width === 390 || width === 1440) {
      for (const theme of ['Light', 'Dark']) {
        await page.getByRole('radio', { name: theme, exact: true }).check()
        await page.screenshot({ path: testInfo.outputPath(`library-${width}-${theme}.png`) })
      }
    }
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('radio', { name: 'Light', exact: true }).check()
  const menu = () => page.getByRole('button', { name: `More actions for ${name}`, exact: true }).click()
  await menu()
  await page.getByRole('menuitem', { name: 'Edit details', exact: true }).click()
  const edit = page.getByRole('dialog', { name: 'Edit slide details', exact: true })
  for (const [label, value] of [['Description', 'Synthetic metadata'], ['Case ID', 'QA-CASE'],
    ['Organ / site', 'QA organ'], ['Stain', 'QA stain'], ['Diagnosis', 'QA diagnosis'],
    ['Course', 'QA course'], ['Tags (comma separated)', 'qa-tag'], ['Teaching note', 'QA teaching'],
    ['Administrator note', 'Private synthetic note']]) {
    await edit.getByRole('textbox', { name: label, exact: true }).fill(value)
  }
  await edit.getByRole('button', { name: 'Save details', exact: true }).click()
  await expect(edit).not.toBeVisible()
  await page.reload()
  await menu()
  await page.getByRole('menuitem', { name: 'Edit details', exact: true }).click()
  await expect(edit.getByRole('textbox', { name: 'Administrator note', exact: true })).toHaveValue('Private synthetic note')
  await edit.getByRole('button', { name: 'Close Edit slide details', exact: true }).click()
  const detailsPanel = page.getByRole('complementary', { name: 'Slide details', exact: true })
  await detailsPanel.getByRole('button', { name: 'Close slide details', exact: true }).click()
  await expect(detailsPanel).not.toBeVisible()
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  for (const [label, value] of [['Organ / site', 'QA organ'], ['Stain', 'QA stain'],
    ['Diagnosis', 'QA diagnosis'], ['Course', 'QA course'], ['Processing state', 'ready_private']]) {
    await page.getByRole('combobox', { name: label, exact: true }).selectOption(value)
  }
  await page.getByRole('textbox', { name: 'Tag', exact: true }).fill('qa-tag')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await expect(page).toHaveURL(/qa-tag/)
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Filters', exact: true }).click()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await page.getByRole('button', { name: 'Close filters', exact: true }).click()

  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByRole('menuitem', { name: 'New folder', exact: true }).click()
  const folder = page.getByRole('dialog', { name: 'New folder', exact: true })
  await folder.getByLabel('Name', { exact: true }).fill('QA shared folder')
  await folder.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(folder).not.toBeVisible()
  await menu()
  await page.getByRole('menuitem', { name: 'Move', exact: true }).click()
  const move = page.getByRole('dialog', { name: 'Move slides', exact: true })
  await move.getByRole('combobox', { name: 'Destination', exact: true }).selectOption({ label: 'QA shared folder' })
  await move.getByRole('button', { name: 'Move', exact: true }).click()
  await expect(move).not.toBeVisible()
  await page.getByRole('button', { name: 'Slide library', exact: true }).click()
  await page.locator('#library-navigator').getByText('QA shared folder', { exact: true }).first().click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Share', exact: true }).click()
  const share = page.getByRole('dialog', { name: 'Share QA shared folder', exact: true })
  await share.locator('label').filter({ hasText: 'I confirm public names' }).click()
  await expect(share.getByRole('checkbox', { name: /I confirm public names/ })).toBeChecked()
  await share.getByRole('button', { name: 'Create shared link', exact: true }).click()
  const link = share.getByRole('textbox', { name: 'Shared link', exact: true })
  await expect(link).toBeVisible()
  const previous = await link.inputValue()
  const anonymous = await browser.newContext()
  try {
    const viewer = await anonymous.newPage()
    await viewer.goto(previous)
    await expect(viewer.getByRole('heading', { name, exact: true })).toBeVisible()
    await share.getByRole('button', { name: 'Rotate', exact: true }).click()
    await expect(link).not.toHaveValue(previous)
    const current = await link.inputValue()
    const oldId = new URL(previous).pathname.split('/').pop()
    expect((await page.request.get(`/api/v2/public/folders/${oldId}`)).status()).toBe(404)
    await viewer.goto(current)
    await expect(viewer.getByRole('heading', { name, exact: true })).toBeVisible()
    fault('expire-share', new URL(current).pathname.split('/').pop())
    await viewer.reload()
    await expect(viewer.getByRole('heading', { name: 'This shared library is unavailable', exact: true })).toBeVisible()
    await share.getByRole('button', { name: 'Revoke', exact: true }).click()
    await share.getByRole('button', { name: 'Confirm revoke', exact: true }).click()
    await expect(share.getByText('Shared link revoked.', { exact: true })).toBeVisible()
    const currentId = new URL(current).pathname.split('/').pop()
    expect((await page.request.get(`/api/v2/public/folders/${currentId}`)).status()).toBe(404)
  } finally { await anonymous.close() }
  await share.getByRole('button', { name: 'Close Share QA shared folder', exact: true }).click()
  await menu()
  await page.getByRole('menuitem', { name: 'Move to Trash', exact: true }).click()
  await page.goto('/admin?location=trash')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await menu()
  await page.getByRole('menuitem', { name: 'Restore', exact: true }).click()
  await page.goto('/admin')
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await page.getByRole('menuitem', { name: 'New collection', exact: true }).click()
  const collection = page.getByRole('dialog', { name: 'New collection', exact: true })
  await collection.getByLabel('Name', { exact: true }).fill('QA bulk collection')
  await collection.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(collection).not.toBeVisible()
  await page.getByRole('checkbox', { name: `Select ${name}`, exact: true }).press('Space')
  await expect(page.getByRole('checkbox', { name: `Select ${name}`, exact: true })).toBeChecked()
  await page.getByRole('toolbar', { name: 'Selection actions' }).getByRole('button', { name: 'Edit tags', exact: true }).click()
  const tags = page.getByRole('dialog', { name: 'Edit tags', exact: true })
  await tags.getByLabel('Tags', { exact: true }).fill('QA bulk tag, QA second tag')
  await tags.getByRole('button', { name: 'Save tags', exact: true }).click()
  await expect(tags).not.toBeVisible()
  await page.reload()
  await expect(page.getByText('QA bulk tag', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: `Select ${name}`, exact: true }).press('Space')
  await expect(page.getByRole('checkbox', { name: `Select ${name}`, exact: true })).toBeChecked()
  await page.getByRole('toolbar', { name: 'Selection actions' }).getByRole('button', { name: 'Add to collection', exact: true }).click()
  const add = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Add to collection', exact: true }) })
  await testInfo.attach('collection-dialog-accessibility', { contentType: 'application/json', body: JSON.stringify(await add.evaluate((element) => ({
    label: element.getAttribute('aria-labelledby'),
    heading: element.querySelector('h2')?.outerHTML,
    labelMatches: document.querySelectorAll(`[id="${element.getAttribute('aria-labelledby')}"]`).length,
  }))) })
  await expect(add).toHaveAccessibleName('Add to collection')
  await add.getByRole('combobox', { name: 'Collection', exact: true }).selectOption({ label: 'QA bulk collection' })
  await add.getByRole('button', { name: 'Add slides', exact: true }).click()
  await expect(add).not.toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: `Open details for ${name}`, exact: true }).click()
  await expect(page.getByRole('complementary', { name: 'Slide details' }).getByText('QA bulk collection', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close slide details', exact: true }).click()
  await page.getByRole('button', { name: /^Open storage,/ }).click()
  await page.getByRole('searchbox', { name: 'Search stored files', exact: true }).fill(name)
  await expect(page.getByRole('row').filter({ hasText: name })).toHaveCount(1)
  await page.getByRole('button', { name: `Move to Trash: ${name}`, exact: true }).click()
  await expect(page.getByRole('button', { name: `Restore: ${name}`, exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: `Restore: ${name}`, exact: true }).click()
  await expect(page.getByRole('button', { name: `Move to Trash: ${name}`, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Back to slide library', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
})
