import { expect, test } from './qa-test'
import { signIn } from '../e2e-live/capacity-helpers'
import { fault } from './fixture-faults'

test('rostered learner submits text; teacher grades, releases, exports, archives and restores', async ({ page, browser }) => {
  // Build this test's own course so it is runnable by title in an empty database.
  await page.getByRole('button', { name: 'Teaching Studio', exact: true }).click()
  await page.getByRole('link', { name: 'Courses', exact: true }).click()
  await page.getByRole('link', { name: 'Create course', exact: true }).click()
  for (const [label, value] of [['Course name', 'QA grading course'], ['Course ID', 'QA-GRADE'], ['Semester', '1'], ['Academic year', '2026']]) {
    await page.getByRole('textbox', { name: new RegExp(label) }).fill(value)
  }
  await page.getByRole('button', { name: 'Save course', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Edit course', exact: true })).toBeVisible()
  const courseUrl = page.url()
  await page.getByRole('link', { name: 'Manage roster', exact: true }).click()
  await page.getByText('Paste rows instead', { exact: true }).click()
  await page.getByRole('textbox', { name: /^Roster rows/ }).fill('student_id,given_name,surname,group\nQAGRADE,Synthetic,Grading,A')
  await page.getByRole('button', { name: 'Import roster', exact: true }).click()
  await expect(page.getByText('QAGRADE', { exact: true })).toBeVisible()
  await page.goto(courseUrl)
  await page.getByRole('link', { name: 'New class', exact: true }).first().click()
  await page.getByRole('textbox', { name: 'Class name', exact: true }).fill('QA grading class')
  await page.getByRole('textbox', { name: 'Section code', exact: true }).fill('QA-G')
  await page.getByRole('button', { name: 'Save class', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'QA grading class', exact: true })).toBeVisible()
  await page.goto('/admin/assessments')
  await page.getByRole('button', { name: 'New assessment', exact: true }).click()
  await page.getByRole('combobox', { name: 'Course', exact: true }).selectOption({ label: 'QA grading course · QA-GRADE' })
  await page.getByRole('combobox', { name: 'Class', exact: true }).selectOption({ label: 'QA grading class · QA-G' })
  await page.getByRole('button', { name: 'Create assessment', exact: true }).click()
  await page.getByRole('button', { name: 'Upgrade to sections', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Question type for section 1', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Assessment name', exact: true }).fill('QA manual grading')
  await page.getByRole('combobox', { name: 'Question type for section 1', exact: true }).selectOption('short-answer')
  await page.getByRole('button', { name: 'Add selected question to section 1', exact: true }).click()
  await page.getByRole('textbox', { name: 'Question', exact: true }).fill('Describe the synthetic specimen')
  await page.getByText('Answer key & keywords', { exact: true }).click()
  await page.getByRole('checkbox', { name: 'Review responses manually instead of auto-scoring', exact: true }).check()
  await expect(page.getByText('All changes saved', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  const publish = page.getByRole('dialog', { name: 'Publish assessment', exact: true })
  await publish.getByRole('combobox', { name: 'Mode', exact: true }).selectOption('formative')
  await publish.getByRole('checkbox', { name: 'QA grading class', exact: true }).check()
  const publication = page.waitForResponse((response) => response.request().method() === 'POST' && response.url().includes('/publish'))
  await publish.getByRole('button', { name: 'Publish assignment', exact: true }).click()
  const published = await publication
  expect(published.ok(), await published.text()).toBe(true)
  await publish.getByRole('button', { name: 'Open responses', exact: true }).click()
  await expect(publish.getByText('Accepting responses. You can share this link.', { exact: true })).toBeVisible()
  const href = await publish.locator('a[href*="/assessment/"]').last().getAttribute('href')
  const accessCode = (await publish.getByText(/^One-time access code:/).textContent())!.split(':').slice(1).join(':').trim()
  const learner = await browser.newContext()
  try {
    const student = await learner.newPage()
    await student.goto(href!)
    await student.getByRole('textbox', { name: 'Access code', exact: true }).fill(accessCode)
    const searchResponse = student.waitForResponse((response) => response.url().includes('/roster-search'))
    await student.getByRole('combobox', { name: 'Find your roster record', exact: true }).fill('QAGRADE')
    const roster = await searchResponse
    expect(roster.ok(), await roster.text()).toBe(true)
    expect((await roster.json()).items, 'Published class roster').toHaveLength(1)
    await student.getByRole('option').filter({ hasText: 'QAGRADE' }).getByRole('button').click()
    await student.getByRole('button', { name: 'Begin assessment', exact: true }).click()
    await student.getByRole('textbox', { name: 'Answer', exact: true }).fill('Synthetic grading answer')
    await expect(student.getByText(/ · Saved$/)).toBeVisible()
    await student.reload()
    await expect(student.getByRole('textbox', { name: 'Answer', exact: true })).toHaveValue('Synthetic grading answer')
    await student.getByRole('button', { name: 'Submit assessment', exact: true }).click()
    await student.getByRole('button', { name: 'Submit assessment', exact: true }).click()
    await expect(student.getByRole('heading', { name: 'Assessment submitted', exact: true })).toBeVisible()
    await publish.getByRole('button', { name: 'Close publish settings', exact: true }).click()
    await page.getByRole('tab', { name: 'Responses', exact: true }).click()
    await page.getByRole('button', { name: /^Needs grading/ }).click()
    await page.getByRole('spinbutton', { name: 'Points', exact: true }).fill('0')
    await page.getByRole('textbox', { name: 'Feedback', exact: true }).fill('Synthetic feedback')
    await page.getByRole('button', { name: 'Save & next', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Grading complete', exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Grading complete', exact: true })).toBeVisible()
    await page.getByRole('switch', { name: 'Accepting responses', exact: true }).click()
    await page.getByRole('button', { name: 'Release scores', exact: true }).click()
    await student.reload()
    await expect(student.getByText(/^0(?:\.0+)? \/ 1(?:\.0+)?$/)).toBeVisible()
    for (const format of ['CSV', 'Excel', 'Visual']) {
      const downloading = page.waitForEvent('download')
      await page.getByRole('link', { name: format, exact: true }).click()
      expect(await (await downloading).failure()).toBeNull()
    }
  } finally { await learner.close() }
  await page.goto('/admin/assessments')
  await page.getByRole('button', { name: /^Archive QA manual grading,/ }).click()
  await expect(page.getByRole('button', { name: 'Restore QA manual grading', exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Restore QA manual grading', exact: true }).click()
  await expect(page.getByRole('button', { name: /^Archive QA manual grading,/ })).toBeVisible()
})

test.beforeEach(async ({ page }) => {
  fault('expire-assessment-cooldown')
  await signIn(page, process.env.PATHLAB_E2E_USERNAME!, process.env.PATHLAB_E2E_PASSWORD!)
})

test('synthetic course, roster and class persist through Teaching Studio', async ({ page }) => {
  await page.getByRole('button', { name: 'Teaching Studio', exact: true }).click()
  await page.getByRole('link', { name: 'Courses', exact: true }).click()
  await page.getByRole('link', { name: 'Create course', exact: true }).click()
  for (const [label, value] of [['Course name', 'QA synthetic course'], ['Course ID', 'QA-20260913'],
    ['Semester', '1'], ['Academic year', '2026']]) {
    await page.getByRole('textbox', { name: new RegExp(label) }).fill(value)
  }
  await page.getByRole('textbox', { name: 'Course description', exact: true }).fill('No real learners. Disposable QA.')
  await page.getByRole('button', { name: 'Save course', exact: true }).click()
  await expect(page.getByRole('link', { name: 'Edit course', exact: true })).toBeVisible()
  const courseUrl = page.url()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'QA synthetic course', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Manage roster', exact: true }).click()
  await page.getByText('Paste rows instead', { exact: true }).click()
  await page.getByRole('textbox', { name: /^Roster rows/ }).fill('student_id,given_name,surname,group\nQA0001,Synthetic,Learner,A')
  await page.getByRole('button', { name: 'Import roster', exact: true }).click()
  await expect(page.getByText('QA0001', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('QA0001', { exact: true })).toBeVisible()
  await page.goto(courseUrl)
  await page.getByRole('link', { name: 'New class', exact: true }).first().click()
  await page.getByRole('textbox', { name: 'Class name', exact: true }).fill('QA synthetic class')
  await page.getByRole('textbox', { name: 'Section code', exact: true }).fill('QA-A')
  await page.getByRole('textbox', { name: 'Location', exact: true }).fill('Synthetic lab')
  await page.getByRole('button', { name: 'Save class', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'QA synthetic class', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'QA synthetic class', exact: true })).toBeVisible()
})

test('author, publish, answer and submit an anonymous formative assessment', async ({ page, browser }) => {
  await page.getByRole('button', { name: 'Teaching Studio', exact: true }).click()
  await page.getByRole('button', { name: 'New assessment', exact: true }).click()
  await page.getByRole('button', { name: 'Create assessment', exact: true }).click()
  await page.getByRole('button', { name: 'Upgrade to sections', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Question type for section 1', exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Assessment name', exact: true }).fill('QA formative journey')
  await page.getByRole('combobox', { name: 'Question type for section 1', exact: true }).selectOption('multiple-choice')
  await page.getByRole('button', { name: 'Add selected question to section 1', exact: true }).click()
  await page.getByRole('textbox', { name: 'Question', exact: true }).fill('Choose the synthetic QA answer')
  await page.getByRole('textbox', { name: 'Option 1', exact: true }).fill('Synthetic A')
  await page.getByRole('textbox', { name: 'Option 2', exact: true }).fill('Synthetic B')
  await page.getByLabel('Correct option 1', { exact: true }).check()
  await expect(page.getByText('All changes saved', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('textbox', { name: 'Assessment name', exact: true })).toHaveValue('QA formative journey')
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  const publish = page.getByRole('dialog', { name: 'Publish assessment', exact: true })
  await publish.getByRole('combobox', { name: 'Mode', exact: true }).selectOption('formative')
  for (const checkbox of await publish.getByRole('checkbox').all()) {
    if (await checkbox.isChecked() && await checkbox.getAttribute('type') === 'checkbox'
      && await checkbox.evaluate((element) => Boolean(element.closest('fieldset')))) await checkbox.uncheck()
  }
  const publishing = page.waitForResponse((response) => response.request().method() === 'POST' && response.url().includes('/publish'))
  await publish.getByRole('button', { name: 'Publish assignment', exact: true }).click()
  const publicationResult = await publishing
  expect(publicationResult.ok(), await publicationResult.text()).toBe(true)
  await publish.getByRole('button', { name: 'Open responses', exact: true }).click()
  await expect(publish.getByText('Accepting responses. You can share this link.', { exact: true })).toBeVisible()
  const href = await publish.locator('a[href*="/assessment/"]').last().getAttribute('href')
  expect(href).toBeTruthy()
  const learner = await browser.newContext({ timezoneId: 'Asia/Bangkok' })
  try {
    const student = await learner.newPage()
    await student.goto(href!)
    await student.getByRole('button', { name: 'Continue anonymously', exact: true }).click()
    await student.getByRole('radio', { name: 'Synthetic A', exact: true }).check()
    await expect(student.getByText(/(?:59:\d\d|60:00) · Saved$/)).toBeVisible()
    await student.reload()
    await expect(student.getByRole('radio', { name: 'Synthetic A', exact: true })).toBeChecked()
    await student.getByRole('button', { name: 'Submit assessment', exact: true }).click()
    await student.getByRole('button', { name: 'Submit assessment', exact: true }).click()
    await expect(student.getByRole('heading', { name: 'Assessment submitted', exact: true })).toBeVisible()
  } finally { await learner.close() }
  await publish.getByRole('button', { name: 'Close publish settings', exact: true }).click()
  await page.getByRole('tab', { name: 'Responses', exact: true }).click()
  await expect(page.getByText('1 of 1 learners completed', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('1 of 1 learners completed', { exact: true })).toBeVisible()
  await page.getByRole('switch', { name: 'Accepting responses', exact: true }).click()
  await expect(page.getByRole('switch', { name: 'Accepting responses', exact: true })).toHaveAttribute('aria-checked', 'false')
})
